name: Build Android APK (Fintech)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci || npm i
          npm i -D @capacitor/cli
          npm i @capacitor/android

      - name: Create dummy dist
        run: |
          mkdir -p dist
          echo '<!doctype html><meta charset="utf-8"><title>Fintech</title>' > dist/index.html

      - name: Add & sync Android platform
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug -Dorg.gradle.java.home=$JAVA_HOME_21_X64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fintech-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
